# Generated by Django 5.1.2 on 2024-10-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_additionalproductimage_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalproductimage",
            options={"ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="additionalprojectimage",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="additionalproductimage",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="additionalprojectimage",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
